USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/htc/z4dug/BoardConfigVendor.mk

# Platform
TARGET_BOARD_PLATFORM := msm7x27a
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_GLOBAL_CFLAGS += -mtune=cortex-a5 -mfpu=neon
TARGET_GLOBAL_CPPFLAGS += -mtune=cortex-a5 -mfpu=neon
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE
COMMON_GLOBAL_CFLAGS += -DHTCLOG
BOARD_USES_QCOM_HARDWARE := true
BOARD_VENDOR := htc
TARGET_USE_QCOM_BIONIC_OPTIMIZATION := true

# Architecture
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := false
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a5
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a5

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := z4dug

# Kernel
#TARGET_PREBUILT_KERNEL := device/htc/z4dug/kernel
BOARD_KERNEL_CMDLINE := no_console_suspend=1 console=null
BOARD_KERNEL_BASE := 0x03b00000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 00008000 --ramdisk_offset 01408000 --tags_offset 00000100
TARGET_NO_KERNEL := false

# Partitions
#BOARD_CACHE_DEVICE := /dev/block/mmcblk0p39
#BOARD_CACHE_FILESYSTEM := ext4
#BOARD_CACHE_FILESYSTEM_OPTIONS := rw
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p40
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
BOARD_DATA_DEVICE := /dev/block/mmcblk0p41
BOARD_DATA_FILESYSTEM := ext4
BOARD_DATA_FILESYSTEM_OPTIONS := rw
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 16776192
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16776704
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2013264896
BOARD_CACHEIMAGE_PARTITION_SIZE := 233570304
TARGET_USERIMAGES_USE_EXT4 := true

# Hardware Rendering
TARGET_GPU_PP_CORE := 3
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 2
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_QCOM_DISPLAY_VARIANT := legacy
TARGET_QCOM_HDMI_OUT := false
TARGET_HAVE_HDMI_OUT := false
TARGET_NO_HW_OVERLAY := true
TARGET_USES_GENLOCK := true
TARGET_USES_OVERLAY := true
BOARD_USE_SKIA_LCDTEXT := true

# Generic
BOARD_HAVE_BLUETOOTH := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USES_ION := true
TARGET_RECOVERY_INITRC := device/htc/z4dug/recovery/init.rc
TARGET_SPECIFIC_HEADER_PATH := device/htc/z4dug/include
BOARD_EGL_CFG := device/htc/z4dug/config/egl.cfg
TARGET_NO_HW_VSYNC := true
BOARD_VOLD_MAX_PARTITIONS := 41


CFLAGS_MODULE=-fno-pic
EXTRA_CFLAGS=-fno-pic


# twrp
DEVICE_RESOLUTION := 480x800
TW_INTERNAL_STORAGE_PATH := "/emmc"
TW_INTERNAL_STORAGE_MOUNT_POINT := "emmc"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_DEFAULT_EXTERNAL_STORAGE := true

TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/class/android_usb/android0/f_mass_storage/lun0/file"
BOARD_UMS_LUNFILE := "/sys/class/android_usb/android0/f_mass_storage/lun0/file"

